CRAYSAT-1241: Add `prodmgr` RPM to CSM k8s image
Cray-HPE/csm-rpms pull request #164
Opened 2021-12-07 21:09 UTC by ekamin-hpe

## Summary and Scope

-Add SAT RPM repository to repos/cray.repos
- Add prodmgr RPM to Kubernetes node image by adding it to base.packages

## Issues and Related PRs

- Resolves [CRAYSAT-1241](https://connect.us.cray.com/jira/browse/CRAYSAT-1241)

## Testing

Tested locally by building a Kubernetes NCN image.

### Tested on:

- Local development environment

### Test description:

- Built a squashfs kubernetes image
- Mounted the resulting image and used chroot to check the RPM was installed and the command would run.

## Risks and Mitigations

N/A

## Pull Request Checklist

- [N/A] Version number(s) incremented, if applicable
- [N/A] Copyrights updated
- [N/A] License file intact
- [X] Target branch correct
- [N/A] CHANGELOG.md updated
- [X] Testing is appropriate and complete, if applicable
- [N/A] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2021-12-07 22:34 UTC, rustydb commented
@heemstra , does CRAYSAT-1241 need a `CASM-Release-Ready` label?

2021-12-08 17:37 UTC, rustydb requested changes

2021-12-08 17:37 UTC, rustydb commented on repos/cray.repos
> +https://arti.dev.cray.com/artifactory/sat-rpm-master-local/dev/master//sle15_sp2_ncn/                  cray-sat-sle-15sp2-x86_64-master                  --no-gpgcheck -p 89                   cray/sat
nit: double-slashes.

2021-12-08 19:01 UTC, ekamin-hpe commented on repos/cray.repos
> +https://arti.dev.cray.com/artifactory/sat-rpm-master-local/dev/master//sle15_sp2_ncn/                  cray-sat-sle-15sp2-x86_64-master                  --no-gpgcheck -p 89                   cray/sat
fixed!

2021-12-08 22:08 UTC, rustydb approved these changes

2021-12-08 22:08 UTC, merged