CASMTRIAGE-3784: Use 1.3.2 platform utils
Cray-HPE/csm-rpms pull request #517
Opened 2022-07-26 18:18 UTC by mitchty

### Summary and Scope

- Fixes: CASMTRIAGE-3784
- Requires: https://github.com/Cray-HPE/utils/pull/54
- Relates to: CASMINST-5051

#### Issue Type

- Bugfix Pull Request

Pulls in fixes for the spire token fix script where ssh may fail in certain conditions causing the script not to update the spire storage token and files.
### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [x ] I tested this on internal system (if yes, please include results or a description of the test) Tyr, Drax, Fanta, Mug
- [ ] I tested this on a vshasta system (if yes, please include results or a description of the test)

### Risks and Mitigations
 
As it stands if the cloud init join script fails, and this script is run, depending on what is in ~/.ssh and if the node is in authorized_hosts the fix script won't fix anything.

2022-07-26 18:21 UTC, rgross727 approved these changes

2022-07-26 18:26 UTC, bklei approved these changes

2022-07-26 19:10 UTC, rustydb requested changes
Branch build is failing, that needs to pass before this merges.

2022-07-26 21:48 UTC, mitchty commented
Think I got it working now, learnt not to use replay ever in the jenkins runner.

2022-07-26 21:52 UTC, mitchty commented
Got the branch build issues fixed should be green https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcsm-rpms/detail/PR-517/2/pipeline

2022-07-27 18:17 UTC, rustydb approved these changes

2022-07-27 18:17 UTC, merged