CASMHMS-5743 Fix token leaks in HMS test script
Cray-HPE/csm-rpms pull request #610
Opened 2022-09-13 01:14 UTC by schooler-hpe

### Summary and Scope

This change updates the hpe-csm-scripts version to v0.0.39 which fixes Keycloak authentication token leaks in the hsm_discovery_status_test.sh script. Previously the test output and logs would contain previously used tokens, now these tokens are redacted.

Example output:

```
ncn-m001:~/schooler # ./hsm_discovery_status_test.sh
Running hsm_discovery_status_test...
(17:29:51) Getting client secret...
(17:29:51) Retrieving authentication token...
(17:29:51) Testing 'curl -s -k -H "Authorization: Bearer <REDACTED>" https://api-gw-service-nmn.local/apis/smd/hsm/v2/Inventory/RedfishEndpoints'...
(17:29:51) Processing response with: 'jq '.RedfishEndpoints[] | { ID: .ID, LastDiscoveryStatus: .DiscoveryInfo.LastDiscoveryStatus}' -c | sort -V | jq -c'...
(17:29:52) Verifying endpoint discovery statuses...
PASS: hsm_discovery_status_test passed!
```

### Issues and Related PRs

* Resolves CASMHMS-5743.

### Testing

This change was tested on Fanta by running the updated version of the script under various pass/fail conditions and verifying that the previously printed tokens were no longer present in the test output.

Was a fresh Install tested? Y
Was an Upgrade tested? N/A
Was a Downgrade tested? N/A

### Risks and Mitigations

Low risk, security improvement.

2022-09-13 16:36 UTC, heemstra requested changes
@schooler-hpe - the validation job is not finding a stable artifact for this rpm at this version.

2022-09-13 17:23 UTC, schooler-hpe commented
> @schooler-hpe - the validation job is not finding a stable artifact for this rpm at this version.

Yep, this is expected for now since I haven't tagged the v0.0.39 version yet. I'm still waiting for my base PR to merge before I do that but I wanted to get the manifest PRs out in advance.

2022-09-13 18:30 UTC, rustydb commented
Just merged your hpe-csm-scripts PR.

2022-09-14 18:11 UTC, heemstra approved these changes

2022-09-14 18:12 UTC, merged